tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/completions'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/tex'
tap 'homebrew/versions'
brew 'git'
brew 'bash-completion'
brew 'colordiff'
brew 'exiftool'
brew 'fdupes'
brew 'git-annex'
brew 'gnu-getopt'
brew 'gnu-sed'
brew 'gnupg'
brew 'go'
brew 'handbrake'
brew 'haskell-stack'
brew 'htop'
brew 'hub'
brew 'hugo'
brew 'keychain'
brew 'mas'
brew 'mkvtoolnix', args: ['with-qt']
brew 'mr'
brew 'node'
brew 'openssl@1.1'
brew 'paperkey'
brew 'parallel'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'python3'
brew 'rbenv'
brew 'rclone'
brew 'rmlint'
brew 's3cmd'
brew 'scons'
brew 'shellcheck'
brew 'sphinx-doc'
brew 'ssh-copy-id'
brew 'tree'
brew 'vcsh'
brew 'vim', args: ['with-lua']
brew 'wget'
brew 'youtube-dl'
brew 'zopfli'
cask 'alfred'
cask 'appcleaner'
cask 'arq'
cask 'bartender'
cask 'caffeine'
cask 'ctivo'
cask 'devonthink-pro-office'
cask 'dropbox'
cask 'google-chrome'
cask 'hazel'
cask 'iterm2'
cask 'keyboard-maestro'
cask 'nvalt'
cask 'rowanj-gitx'
cask 'superduper'
cask 'vlc'
mas '1Blocker', id: 1107421413
mas '1Password', id: 443987910
mas 'Bible Study', id: 472790630
mas 'Growl', id: 467939042
mas 'Install Mac OS X Lion', id: 444303913
mas 'Moom', id: 419330170
mas 'Numbers', id: 409203825
mas 'PDF Expert', id: 1055273043
mas 'Screens', id: 446107677
mas 'SiteSucker', id: 442168834
